### PR TITLE
Add link to Quorum Explorer

### PR DESCRIPTION
**Pull request by tinco**

### CODE REVIEW

**Comment by robertDurst** [comment]
@tinco link didn't work for me.

**Comment by robertDurst** [comment]
Nice domain tho +1

**Comment by tinco** [comment]
Ah, can we hold this PR for up to 24h? I think my registrar is being slow.

**Comment by robertDurst** [comment]
Yep we can hodl.

**Comment by robertDurst** [comment]
I see it is live.

**Pull request merged**
