### PR TITLE
Added Unity 3D SDK to the list

### PR DESCRIPTION
**Pull request by Kirbyrawr**

### CODE REVIEW

**Comment by endingwithali** [comment]
Hey - turns out theres some merge conflicts -- can you go in and fix them?

thanks 

Also, make sure there are two spaces after your last period :)

**Comment by Kirbyrawr** [comment]
Thank you, will do it today!

**Comment by Kirbyrawr** [comment]
Seems okay to me now, let me know if something is wrong, and thank you again @asfink !

**Comment by Kirbyrawr** [comment]
I previewed it since i wasn't sure it was totally ok, and i fixed it one more time (I'm bad with docs, sorry).
Now seems totally ok!

**Review by endingwithali — APPROVED** [review]

**Pull request merged**
